package com.callblockerpro.app.data.mapper

import com.callblockerpro.app.data.local.entity.BlocklistEntity
import com.callblockerpro.app.data.local.entity.WhitelistEntity
import com.callblockerpro.app.domain.model.BlocklistEntry
import com.callblockerpro.app.domain.model.WhitelistEntry

fun WhitelistEntity.toDomain() = WhitelistEntry(
    id = id,
    phoneNumber = phoneNumber,
    name = name,
    notes = notes,
    createdAt = createdAt,
    updatedAt = updatedAt
)

fun BlocklistEntity.toDomain() = BlocklistEntry(
    id = id,
    phoneNumber = phoneNumber,
    name = name,
    reason = reason,
    createdAt = createdAt,
    updatedAt = updatedAt
)

fun WhitelistEntry.toEntity() = WhitelistEntity(
    // ID autogenerated on insert for new entries, but if mapping back for updates we might need it. 
    // For now we assume new entries or we ignore ID if 0.
    phoneNumber = phoneNumber,
    name = name,
    notes = notes,
    createdAt = createdAt,
    updatedAt = updatedAt
)

fun BlocklistEntry.toEntity() = BlocklistEntity(
    phoneNumber = phoneNumber,
    name = name,
    reason = reason,
    createdAt = createdAt,
    updatedAt = updatedAt
)
